# @package _global_
# 论文实验：AIME24评估配置（训练后的增强agent）
defaults:
  - /agents/practice/math_practice_paper_exp_agent@agent
  - _self_

exp_id: "math_AIME24_no_tools_practice"

data:
  dataset: "AIME24"

concurrency: 32                  # 并发数（可根据机器性能调整）
pass_k: 32                       # pass@k评估

verify_filename: "math.py"
verify_func_name: "verify_func"

