# @package _global_
defaults:
  - /agents/practice/logic_medium_normal_num1@agent
  - _self_

exp_id: "easy_practice_normal_num1"

data:
  dataset: "ZebraLogic-Easy-30"

concurrency: 32
pass_k: 5

verify_filename: "logic.py"
verify_func_name: "verify_func"

