# @package _global_
defaults:
  - /agents/practice/logic_sum@agent
  - _self_

exp_id: "zebralogic_structured_practice_sum"

data:
  dataset: "ZebraLogic-Test-30-Medium"

concurrency: 32
pass_k: 32

verify_filename: "logic.py"
verify_func_name: "verify_func"

