# @package _global_
defaults:
  - /agents/practice/logic_easy_enhance_num1@agent
  - _self_

exp_id: "medium_practice_enhance_num1"

data:
  dataset: "ZebraLogic-Medium-30"

concurrency: 32
pass_k: 5

verify_filename: "logic.py"
verify_func_name: "verify_func"

