# @package _global_
defaults:
  - /agents/practice/logic_agent_zebralogic_base_template@agent
  - _self_

exp_id: "qwen_baseline_basepro_easy_1"

data:
  dataset: "ZebraLogic-Easy-30"

concurrency: 32
pass_k: 5

verify_filename: "logic.py"
verify_func_name: "verify_func"

