# @package _global_
defaults:
  - /agents/practice/logic_agent_basepro@agent
  - _self_

exp_id: "qwen_practice_easy_basepro_num2"

data:
  dataset: "ZebraLogic-Easy-30"

concurrency: 32
pass_k: 5

verify_filename: "logic.py"
verify_func_name: "verify_func"

