# @package _global_
defaults:
  - /agents/practice/logic_agent_zebralogic_structured@agent
  - _self_

exp_id: "qwen_medium_base"

data:
  dataset: "ZebraLogic-Medium-30"

concurrency: 32
pass_k: 5

verify_filename: "logic.py"
verify_func_name: "verify_func"

